[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dagger"
requires-python = ">= 3.10"
version = "0.0.1"
dependencies = [
    "pytest"
]

#[project.scripts]
#dagger_script = "dagger:dagger_script"

[tool.setuptools]
include-package-data = true

